name: Run Dagger pipeline

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:

jobs:
  dagger:
    name: Run Dagger pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
          cache: false

      - name: Run Dagger pipeline
        uses: dagger/dagger-for-github@v5
        with:
          verb: run
          args: go run pipeline.go
          version: "0.12.5"